export const SmallBNumberList = [{
    key: "core",
    name: "核心小B数",
    symbol: "x",
    extraText: "指今年（自然年）消费2w及以上的雇主数"
}, {
    key: "avg",
    name: "年均消费额",
    unit: "万",
    symbol: "x",
    extraText: "年均消费额：年均消费额=雇主总消费金额/核心小B数，雇主总消费金额包括：设计、IT、营销、综合、知产、财税、科技服务、企业管家、总分包订单打款金额，其中企业管家、总分包指分包订单结算金额"
}, {
    key: "keyb",
    name: "商业变现率",
    symbol: "=",
    placeholder: "--"
}, {
    key: "keyb",
    name: "收入",
    placeholder: "--"
}];
export const TopCardList = [{
    name: "收入",
    key: "income"
}, {
    name: "成本",
    key: "income"
}, {
    name: "交易收入",
    key: "income"
}, {
    name: "人均毛利",
    key: "income"
}];
export const TabLink = [{
    link: "/manager/user",
    name: "用户分析",
    component: "CeoUser",
    key: "user"
}, {
    link: "/manager/flowanalysis",
    name: "流量分析",
    component: "CeoFlowAnalysis",
    key: "flowanalysis"
}, {
    link: "/manager/traffic",
    name: "热力图",
    component: "CeoTraffic",
    key: "traffic"
}, {
    link: "/manager/Convert",
    name: "流量转化分析",
    component: "CeoConvert",
    key: "convert"
}, {
    link: "/manager/index",
    name: "营收分析",
    component: "CeoIncome",
    key: "income"
}, {
    link: "/manager/order",
    name: "订单分析",
    component: "CeoOrder",
    key: "order"
}, {
    link: "/manager/employ",
    name: "雇主分析",
    component: "CeoEmploy",
    key: "employe"
}, {
    link: "/manager/service",
    name: "服务商分析",
    component: "CeoService",
    key: "service"
}, {
    link: "/manager/zwork",
    name: "八戒工场分析",
    component: "CeoZwork",
    key: "zwork"
}, {
    link: "/manager/manager",
    name: "企业管家分析",
    component: "CeoManager",
    key: "manager"
}, {
    link: "/manager/hr",
    name: "人力分析",
    component: "CeoHr",
    key: "hr"
}, {
    link: "/manager/heatsearch",
    name: "热搜热力图",
    component: "CeoHeatSearch",
    key: "heatsearch"
}, {
    link: "/manager/trafficdetail",
    name: "",
    component: "CeoTrafficDetail",
    key: "trafficdetail"
}, {
    link: "/manager/heatsearchsecond",
    name: "",
    component: "CeoHeatSearchSecond",
    key: "heatsearchsecond"

},];